Require SUNDIALS 2.5.0. Detect problems with integer sizes.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -120,8 +120,8 @@ else
     sundials_version=`echo ${sundials_info} | sed -ne 's/"\(.*\)",./\1/p'`
 
     case "${sundials_version}" in
-	[0-1].*.* | 2.[0-3].*)
-	    error="${error}\n\tsundials >= 2.4.0 required" ;;
+	[0-1].*.* | 2.[0-4].*)
+	    error="${error}\n\tsundials >= 2.5.0 required" ;;
 	*) ;;
     esac
 
@@ -134,6 +134,62 @@ else
 	*)
 	    error"${error}\n\terror interpreting sundials_config.h" ;;
     esac
+fi
+
+query="#include <caml/mlvalues.h>\nSIZEOF_INT,SIZEOF_LONG,SIZEOF_PTR"
+ilp_size=`echo ${query} | ${CPP} -P | tail -1`
+int_size=`expr "$ilp_size" : "^\([^,]*\),*"`
+long_size=`expr "$ilp_size" : "^[^,]*,\([^,]*\),*"`
+ptr_size=`expr "$ilp_size" : "^[^,]*,[^,]*,\([^,]*\)"`
+if echo $int_size | grep -q '[^0-9]'; then
+    echo "Failed to detect size of \`int'.  This might be a problem"
+    echo "with detecting your system's C preprocessor."
+    echo
+    exit 1
+fi
+if echo $long_size | grep -q '[^0-9]'; then
+    echo "Failed to detect size of \`long'.  This might be a problem"
+    echo "with detecting your system's C preprocessor."
+    echo
+    exit 1
+fi
+if echo $ptr_size | grep -q '[^0-9]'; then
+    echo "Failed to detect size of pointers.  This might be a problem"
+    echo "with detecting your system's C preprocessor."
+    echo
+    exit 1
+fi
+
+if [ "${long_size}" -ne "${ptr_size}" ]; then
+    error="${error}\nsizeof (long) does not match sizeof (void*)."
+    error="${error}\nStarting with SUNDIALS version 2.5.0, DenseGETRF() and"
+    error="${error}\nsimilar functions require arrays of longs as input,"
+    error="${error}\nso this binding needs to map C's long * type to some OCaml"
+    error="${error}\ntype.  We chose to map it to bigarray with int entries,"
+    error="${error}\nwhich gives an overhead-free mapping and a convenient API"
+    error="${error}\nfor the user.  As a downside, this requires C's long type"
+    error="${error}\nto have the same size as OCaml values, i.e. the same size"
+    error="${error}\nas pointers.  The only platform known to violate this"
+    error="${error}\nrequirement is Microsoft Visual C on 64-bit Windows"
+    error="${error}\n(Win64).  If you must use this binding on 64-bit Windows,"
+    error="${error}\ntry compiling SUNDIALS and the binding with Cygwin.  If"
+    error="${error}\nusing Cygwin is not an option, write to us and we may"
+    error="${error}\nbe able to hack together a workaround for Win64, albeit"
+    error="${error}\nwith a slight performance hit."
+fi
+if [ "${int_size}" -ne 4 ]; then
+    error="${error}\nint is not 32 bits on this platform."
+    error="${error}\nSome SUNDIALS functions require arrays of ints as input,"
+    error="${error}\nso this binding needs to map C's int * type to some OCaml"
+    error="${error}\ntype.  We chose to map it to bigarray with int32 entries"
+    error="${error}\nwhich gives an overhead-free mapping and a convenient API"
+    error="${error}\nfor the user, provided that C's int type is 32 bits.  This"
+    error="${error}\nis the case with most, if not all, 32-bit and 64-bit"
+    error="${error}\nsystems, and we were not aware of any platforms that are "
+    error="${error}\nstill in use which violate this requirement.  However, it"
+    error="${error}\nlooks like you have such a platform.  Please inform us"
+    error="${error}\nabout your platform and we may be able to hack together a"
+    error="${error}\nworkaround, albeit with a slight performance hit."
 fi
 
 if [ "${lapack_lib}" = "" ]; then
